In [1]:
import pandas as pd 
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr,sent

([[1130, 1064, 9741, 5745],
  [1130, 1064, 9741, 1879],
  [1130, 5602, 9741, 4785],
  [5052, 4924, 3428, 9704, 752],
  [5052, 4924, 3428, 9704, 3278],
  [1746, 1130, 3385, 9741, 242],
  [8720, 2327, 2833, 9704]],
 ['the glass of milk',
  'the glass of juice',
  'the cup of tea',
  'I am a good boy',
  'I am a good developer',
  'understand the meaning of words',
  'your videos are good'])

In [6]:
### word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1130 1064 9741 5745]
 [   0    0    0    0 1130 1064 9741 1879]
 [   0    0    0    0 1130 5602 9741 4785]
 [   0    0    0 5052 4924 3428 9704  752]
 [   0    0    0 5052 4924 3428 9704 3278]
 [   0    0    0 1746 1130 3385 9741  242]
 [   0    0    0    0 8720 2327 2833 9704]]


In [8]:
#feature repsentaton
dim=10

In [9]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=8))
model.compile(optimizer='adam', loss='mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 86ms/step


array([[[-4.41243313e-02,  2.34032534e-02,  1.64950006e-02,
          4.62311171e-02, -7.20090792e-03,  1.79894306e-02,
          6.09664991e-03,  4.80581447e-03,  7.27199018e-04,
          2.79197134e-02],
        [-4.41243313e-02,  2.34032534e-02,  1.64950006e-02,
          4.62311171e-02, -7.20090792e-03,  1.79894306e-02,
          6.09664991e-03,  4.80581447e-03,  7.27199018e-04,
          2.79197134e-02],
        [-4.41243313e-02,  2.34032534e-02,  1.64950006e-02,
          4.62311171e-02, -7.20090792e-03,  1.79894306e-02,
          6.09664991e-03,  4.80581447e-03,  7.27199018e-04,
          2.79197134e-02],
        [-4.41243313e-02,  2.34032534e-02,  1.64950006e-02,
          4.62311171e-02, -7.20090792e-03,  1.79894306e-02,
          6.09664991e-03,  4.80581447e-03,  7.27199018e-04,
          2.79197134e-02],
        [-7.58398697e-03, -4.29173000e-02,  1.18807442e-02,
         -2.36149319e-02, -4.84534018e-02, -2.84610149e-02,
         -4.42949645e-02, -2.33794581e-02,  3.167972

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 1130, 1064, 9741, 5745])

In [13]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 36ms/step


array([[-4.4124331e-02,  2.3403253e-02,  1.6495001e-02,  4.6231117e-02,
        -7.2009079e-03,  1.7989431e-02,  6.0966499e-03,  4.8058145e-03,
         7.2719902e-04,  2.7919713e-02],
       [-4.4124331e-02,  2.3403253e-02,  1.6495001e-02,  4.6231117e-02,
        -7.2009079e-03,  1.7989431e-02,  6.0966499e-03,  4.8058145e-03,
         7.2719902e-04,  2.7919713e-02],
       [-4.4124331e-02,  2.3403253e-02,  1.6495001e-02,  4.6231117e-02,
        -7.2009079e-03,  1.7989431e-02,  6.0966499e-03,  4.8058145e-03,
         7.2719902e-04,  2.7919713e-02],
       [-4.4124331e-02,  2.3403253e-02,  1.6495001e-02,  4.6231117e-02,
        -7.2009079e-03,  1.7989431e-02,  6.0966499e-03,  4.8058145e-03,
         7.2719902e-04,  2.7919713e-02],
       [-7.5839870e-03, -4.2917300e-02,  1.1880744e-02, -2.3614932e-02,
        -4.8453402e-02, -2.8461015e-02, -4.4294965e-02, -2.3379458e-02,
         3.1679723e-02,  1.6983185e-02],
       [ 3.1467620e-02,  1.8601641e-03,  4.3766644e-02, -3.9583333e-03,
   