In [15]:
import pandas as pd 
from tensorflow.keras.preprocessing.text import one_hot

In [16]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [17]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [18]:
## Define the vocabulary size
voc_size=10000

In [19]:
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr,sent

([[7750, 6673, 5097, 5808],
  [7750, 6673, 5097, 7829],
  [7750, 3530, 5097, 2321],
  [804, 8055, 6566, 6554, 4477],
  [804, 8055, 6566, 6554, 2446],
  [9478, 7750, 9171, 5097, 7366],
  [2536, 9618, 5106, 6554]],
 ['the glass of milk',
  'the glass of juice',
  'the cup of tea',
  'I am a good boy',
  'I am a good developer',
  'understand the meaning of words',
  'your videos are good'])

In [20]:
### word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [21]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7750 6673 5097 5808]
 [   0    0    0    0 7750 6673 5097 7829]
 [   0    0    0    0 7750 3530 5097 2321]
 [   0    0    0  804 8055 6566 6554 4477]
 [   0    0    0  804 8055 6566 6554 2446]
 [   0    0    0 9478 7750 9171 5097 7366]
 [   0    0    0    0 2536 9618 5106 6554]]


In [22]:
#feature repsentaton
dim=10

In [23]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=8))
model.compile(optimizer='adam', loss='mse')

In [24]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [25]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 45ms/step


array([[[ 3.99610065e-02,  1.32246055e-02,  2.26849578e-02,
          2.35495903e-02, -1.63187981e-02,  2.64252760e-02,
         -4.56548333e-02, -4.95006107e-02, -1.57200694e-02,
          4.31513824e-02],
        [ 3.99610065e-02,  1.32246055e-02,  2.26849578e-02,
          2.35495903e-02, -1.63187981e-02,  2.64252760e-02,
         -4.56548333e-02, -4.95006107e-02, -1.57200694e-02,
          4.31513824e-02],
        [ 3.99610065e-02,  1.32246055e-02,  2.26849578e-02,
          2.35495903e-02, -1.63187981e-02,  2.64252760e-02,
         -4.56548333e-02, -4.95006107e-02, -1.57200694e-02,
          4.31513824e-02],
        [ 3.99610065e-02,  1.32246055e-02,  2.26849578e-02,
          2.35495903e-02, -1.63187981e-02,  2.64252760e-02,
         -4.56548333e-02, -4.95006107e-02, -1.57200694e-02,
          4.31513824e-02],
        [ 7.67656416e-03,  1.27097033e-02, -1.38625614e-02,
          6.81086630e-03,  1.42792501e-02,  3.15772332e-02,
         -4.30425182e-02,  4.64366712e-02,  3.581858

In [26]:
embedded_docs[0]

array([   0,    0,    0,    0, 7750, 6673, 5097, 5808])

In [27]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 39ms/step


array([[ 0.03996101,  0.01322461,  0.02268496,  0.02354959, -0.0163188 ,
         0.02642528, -0.04565483, -0.04950061, -0.01572007,  0.04315138],
       [ 0.03996101,  0.01322461,  0.02268496,  0.02354959, -0.0163188 ,
         0.02642528, -0.04565483, -0.04950061, -0.01572007,  0.04315138],
       [ 0.03996101,  0.01322461,  0.02268496,  0.02354959, -0.0163188 ,
         0.02642528, -0.04565483, -0.04950061, -0.01572007,  0.04315138],
       [ 0.03996101,  0.01322461,  0.02268496,  0.02354959, -0.0163188 ,
         0.02642528, -0.04565483, -0.04950061, -0.01572007,  0.04315138],
       [ 0.00767656,  0.0127097 , -0.01386256,  0.00681087,  0.01427925,
         0.03157723, -0.04304252,  0.04643667,  0.03581859, -0.04038047],
       [ 0.00841136, -0.00730155, -0.04015604, -0.00517656,  0.0001039 ,
         0.00420686,  0.01075862,  0.00808633, -0.00883219, -0.01265349],
       [-0.01778565,  0.03739827, -0.03098609,  0.03922525, -0.01945455,
        -0.01299884,  0.01357793,  0.0243347 